apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranking-deployment
  labels:
    app: ranking
spec:
  selector:
    matchLabels:
      app: ranking
  replicas: 3
  template:
    metadata:
      labels:
        app: ranking
    spec:
      containers:
      - name: ranking
        image: top-coins/ranking
        imagePullPolicy: Never
        ports:
        - name: ranking-service
          containerPort: 3002

---

apiVersion: v1
kind: Service
metadata:
  name: ranking-service
spec:
  selector:
    app: ranking
  ports:
  - port: 3002
    targetPort: ranking-service