// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ranking.proto

package pb_ranking

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RankingRequest struct {
	Limit                uint64   `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankingRequest) Reset()         { *m = RankingRequest{} }
func (m *RankingRequest) String() string { return proto.CompactTextString(m) }
func (*RankingRequest) ProtoMessage()    {}
func (*RankingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_21bf82d369a783c5, []int{0}
}
func (m *RankingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingRequest.Unmarshal(m, b)
}
func (m *RankingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingRequest.Marshal(b, m, deterministic)
}
func (dst *RankingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingRequest.Merge(dst, src)
}
func (m *RankingRequest) XXX_Size() int {
	return xxx_messageInfo_RankingRequest.Size(m)
}
func (m *RankingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RankingRequest proto.InternalMessageInfo

func (m *RankingRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Ranking struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	SortOrder            uint64   `protobuf:"varint,3,opt,name=SortOrder,proto3" json:"SortOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ranking) Reset()         { *m = Ranking{} }
func (m *Ranking) String() string { return proto.CompactTextString(m) }
func (*Ranking) ProtoMessage()    {}
func (*Ranking) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_21bf82d369a783c5, []int{1}
}
func (m *Ranking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ranking.Unmarshal(m, b)
}
func (m *Ranking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ranking.Marshal(b, m, deterministic)
}
func (dst *Ranking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ranking.Merge(dst, src)
}
func (m *Ranking) XXX_Size() int {
	return xxx_messageInfo_Ranking.Size(m)
}
func (m *Ranking) XXX_DiscardUnknown() {
	xxx_messageInfo_Ranking.DiscardUnknown(m)
}

var xxx_messageInfo_Ranking proto.InternalMessageInfo

func (m *Ranking) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Ranking) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Ranking) GetSortOrder() uint64 {
	if m != nil {
		return m.SortOrder
	}
	return 0
}

type RankingResponse struct {
	Items                []*Ranking `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RankingResponse) Reset()         { *m = RankingResponse{} }
func (m *RankingResponse) String() string { return proto.CompactTextString(m) }
func (*RankingResponse) ProtoMessage()    {}
func (*RankingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ranking_21bf82d369a783c5, []int{2}
}
func (m *RankingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingResponse.Unmarshal(m, b)
}
func (m *RankingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingResponse.Marshal(b, m, deterministic)
}
func (dst *RankingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingResponse.Merge(dst, src)
}
func (m *RankingResponse) XXX_Size() int {
	return xxx_messageInfo_RankingResponse.Size(m)
}
func (m *RankingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RankingResponse proto.InternalMessageInfo

func (m *RankingResponse) GetItems() []*Ranking {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*RankingRequest)(nil), "pb_ranking.RankingRequest")
	proto.RegisterType((*Ranking)(nil), "pb_ranking.Ranking")
	proto.RegisterType((*RankingResponse)(nil), "pb_ranking.RankingResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RankingServiceClient is the client API for RankingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RankingServiceClient interface {
	GetRankings(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error)
}

type rankingServiceClient struct {
	cc *grpc.ClientConn
}

func NewRankingServiceClient(cc *grpc.ClientConn) RankingServiceClient {
	return &rankingServiceClient{cc}
}

func (c *rankingServiceClient) GetRankings(ctx context.Context, in *RankingRequest, opts ...grpc.CallOption) (*RankingResponse, error) {
	out := new(RankingResponse)
	err := c.cc.Invoke(ctx, "/pb_ranking.RankingService/GetRankings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingServiceServer is the server API for RankingService service.
type RankingServiceServer interface {
	GetRankings(context.Context, *RankingRequest) (*RankingResponse, error)
}

func RegisterRankingServiceServer(s *grpc.Server, srv RankingServiceServer) {
	s.RegisterService(&_RankingService_serviceDesc, srv)
}

func _RankingService_GetRankings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingServiceServer).GetRankings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb_ranking.RankingService/GetRankings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingServiceServer).GetRankings(ctx, req.(*RankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RankingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb_ranking.RankingService",
	HandlerType: (*RankingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRankings",
			Handler:    _RankingService_GetRankings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ranking.proto",
}

func init() { proto.RegisterFile("ranking.proto", fileDescriptor_ranking_21bf82d369a783c5) }

var fileDescriptor_ranking_21bf82d369a783c5 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0xcc, 0xcb,
	0xce, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2a, 0x48, 0x8a, 0x87, 0x8a,
	0x28, 0xa9, 0x71, 0xf1, 0x05, 0x41, 0x98, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x22,
	0x5c, 0xac, 0x39, 0x99, 0xb9, 0x99, 0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x10, 0x8e,
	0x92, 0x37, 0x17, 0x3b, 0x54, 0x9d, 0x10, 0x1f, 0x17, 0x93, 0x67, 0x0a, 0x58, 0x96, 0x33, 0x88,
	0xc9, 0x33, 0x45, 0x48, 0x88, 0x8b, 0xc5, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x2c, 0x02, 0x66,
	0x0b, 0xc9, 0x70, 0x71, 0x06, 0xe7, 0x17, 0x95, 0xf8, 0x17, 0xa5, 0xa4, 0x16, 0x49, 0x30, 0x83,
	0x0d, 0x42, 0x08, 0x28, 0xd9, 0x70, 0xf1, 0xc3, 0x2d, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x15,
	0xd2, 0xe4, 0x62, 0xcd, 0x2c, 0x49, 0xcd, 0x2d, 0x96, 0x60, 0x54, 0x60, 0xd6, 0xe0, 0x36, 0x12,
	0xd6, 0x43, 0xb8, 0x51, 0x0f, 0xa6, 0x16, 0xa2, 0xc2, 0x28, 0x0a, 0xee, 0xe4, 0xe0, 0xd4, 0xa2,
	0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x0f, 0x2e, 0x6e, 0xf7, 0xd4, 0x12, 0xa8, 0x60, 0xb1, 0x90, 0x14,
	0x36, 0xcd, 0x10, 0xdf, 0x49, 0x49, 0x63, 0x95, 0x83, 0x38, 0x42, 0x89, 0x21, 0x89, 0x0d, 0x1c,
	0x42, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0xd5, 0x4f, 0x4d, 0x32, 0x01, 0x00, 0x00,
}
